package assignment_23_Nov_2022;

import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

public class Que5_ImplementsCollectors {
	public static void main(String[] args) {

		List<Integer>  numbers=Arrays.asList(15,6,74,32,4,8,9);
		
		 List<Integer> collect = numbers.stream().collect(Collectors.toList());
		System.out.println("original list:: " + numbers);
		System.out.println("List generated by Collectors:: " + collect);
	}
}
